import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(containers)/footer/Footer";
// import Navbar from "./(containers)/navbar/Navbar";
import { getServerSession } from "next-auth/next";
import { SessionProvider } from "@/app/(providers)/SessionProvider";
import ReactQueryProvider from "@/app/(providers)/ReactQueryProvider";
import { ThemeProvider } from "./(providers)/ThemeProvider";
import { AuthProvider } from "./(providers)/AuthContext";
import Navbar from "./(containers)/navbar/Navbar";
import ProtectedRoute from "@/hooks/ProtectedRoute";
import { Toaster } from 'react-hot-toast';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  console.log("session", session);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased overflow-hidden`}>
      <Toaster position="top-center" reverseOrder={false} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            
        {/* <SessionProvider session={session}> */}
          {/* <Navbar /> */}
          <ReactQueryProvider>
            <ProtectedRoute>
            {children}
            </ProtectedRoute>
          </ReactQueryProvider>
          <Footer />
        {/* </SessionProvider> */}
        </AuthProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
